### ISSUE TITLE
Running Demo

### ISSUE THREAD

**Issue by jacobfriedman** [SWI-Prolog/packages-paxos#1]
``swipl multicast.pl udp_paxos.pl``

gives _ERROR: /home/jacob/Projects/swi-web-prolog/web-client/lib/paxos/demo/udp_paxos.pl:26: user:main: false_

in the  initialization(main,main)..

When running

``
?- [multicast].
true.
?- [udp_paxos].
true.
?- init_network.
true.
?- a := 343.
``
Gives 
``
% Me@ip(192,168,1,150):43943; starting: []; running: [t(0,3,0,ip(192,168,1,150):37516),t(1,3,0,ip(192,168,1,150):45324)]
% Assigning myself node 2
% Claim 2 ip(192,168,1,150):37516: true
% Claim 2 ip(192,168,1,150):45324: true
% Adding 2 to quorum (now 0x7)
% [Thread paxos_replicator] Starting replicator
% [Thread udp_inbound_proxy] Received quorum proposal 0x7
true.``

Could this be due to the paxos_initialize command? From what I understand, initialization(main, main) gives main as the goal or halts - and if main returns true, evaluation continues. I assume paxos_initialize is the culprit. I will look more into this.

**Comment by JanWielemaker** [comment]
Thanks for reporting.  There was a timing issue in the udp_broadcast library.   This has been fixed in the `clib` package.    If you compiled from source, just do a git pull and all should be fine.  Sorry for the bad start ...

**Comment by jacobfriedman** [comment]
No problem! I had hunch it was something to do with a broadcast timing
mechanism... an early asserted goal completion, I assumed, would have
caused a hiccup compared to the manual start.

Of course, bugs can help us learn more quickly - thank you for both the
testing opportunity and the fix!

J
